spring:
  application:
    name: webpos-product-server

server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
